### ISSUE TITLE
PROTOTIPO-RA

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/prototipo-de-realidad-aumentada-equipo-josue#2]
[Prototipo funcional RA.pdf](https://github.com/SistemasTecTlaxiaco/prototipo-de-realidad-aumentada-equipo-josue/files/6379384/Prototipo.funcional.RA.pdf)

**Comment by AxayacatlS** [comment]
Calificacion 19.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
